events {}

http {
    resolver 127.0.0.11 ipv6=off valid=10s;

    server {
        listen 80;
        server_name _;

        proxy_http_version 1.1;
        proxy_set_header Host $http_host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-Host $http_host;
        proxy_set_header X-Forwarded-Port $server_port;

        location / {
            set $target http://user-service:8000;
            proxy_pass $target;
        }

        location /customer/ {
            set $target http://user-service:8000;
            proxy_pass $target;
        }

        location /staff/ {
            set $target http://user-service:8000;
            proxy_pass $target;
        }

        location /gateway/ {
            set $target http://user-service:8000;
            proxy_pass $target;
        }

        location /api/products/ {
            set $target http://product-service:8000;
            proxy_pass $target;
        }

        location /api/categories/ {
            set $target http://product-service:8000;
            proxy_pass $target;
        }

        location /api/cart/ {
            set $target http://order-service:8000;
            proxy_pass $target;
        }

        location /api/orders/ {
            set $target http://order-service:8000;
            proxy_pass $target;
        }

        location /api/payments/ {
            set $target http://payment-service:8000;
            proxy_pass $target;
        }

        location /api/shipments/ {
            set $target http://shipping-service:8000;
            proxy_pass $target;
        }

        location /api/chat/ {
            set $target http://chatbot-service:8000;
            proxy_pass $target;
        }
    }
}
