"""Static API gateway metadata for the user_service edge."""

SERVICE_DEFINITIONS = (
    {
        "key": "user_service",
        "label": "User Service",
        "role": "Shared auth source, browser-facing UI, and orchestration edge for customer and staff traffic.",
        "localhost": "http://localhost:8000",
        "internal_env": None,
        "internal_default": None,
        "notes": "Terminates browser traffic, owns auth, and fans out to downstream services without duplicating their business logic.",
        "touchpoints": ("Customer app on :8000", "Staff app on :8003"),
    },
    {
        "key": "product_service",
        "label": "Product Service",
        "role": "Unified catalog source for categories, product lists, and product detail payloads.",
        "localhost": "http://localhost:8001",
        "internal_env": "PRODUCT_SERVICE_URL",
        "internal_default": "http://product-service:8000",
        "notes": "Provides catalog data that the gateway normalizes before rendering in the storefront.",
        "touchpoints": ("Category navigation", "Dashboard results", "Product detail"),
    },
    {
        "key": "order_service",
        "label": "Order Service",
        "role": "Internal-first commerce state owner for cart, saved items, compare, checkout, orders, shipping snapshots, and analytics.",
        "localhost": "internal-only",
        "internal_env": "ORDER_SERVICE_URL",
        "internal_default": "http://order-service:8000",
        "notes": "Receives signed internal requests from user_service, then coordinates payment and shipment lifecycle calls.",
        "touchpoints": ("Cart state", "Checkout", "Order history", "Staff shipping snapshots"),
    },
    {
        "key": "payment_service",
        "label": "Payment Service",
        "role": "Internal payment record service for pending and confirmed order payments.",
        "localhost": "internal-only",
        "internal_env": "PAYMENT_SERVICE_URL",
        "internal_default": "http://payment-service:8000",
        "notes": "Called by order_service during checkout and pay-order flows; browser UI does not call it directly.",
        "touchpoints": ("Checkout payment record", "Pay order confirmation"),
    },
    {
        "key": "shipping_service",
        "label": "Shipping Service",
        "role": "Internal shipment record service for recipient snapshots and status transitions.",
        "localhost": "internal-only",
        "internal_env": "SHIPPING_SERVICE_URL",
        "internal_default": "http://shipping-service:8000",
        "notes": "Called by order_service during checkout and staff shipping updates while order_service keeps UI snapshots.",
        "touchpoints": ("Checkout shipment record", "Staff shipping updates"),
    },
    {
        "key": "chatbot_service",
        "label": "Chatbot Service",
        "role": "AI reply generation, retrieval, recommendation ranking, and behavior-aware chat orchestration.",
        "localhost": "http://localhost:8005",
        "internal_env": "CHATBOT_SERVICE_URL",
        "internal_default": "http://chatbot-service:8000",
        "notes": "Serves the proxied chatbot reply endpoint consumed by the website widget and AI suggestion builders.",
        "touchpoints": ("Chat widget", "Dashboard AI block", "Cart AI block"),
    },
)

ROUTE_SECTION_DEFINITIONS = (
    {
        "key": "discovery",
        "title": "Catalog Discovery",
        "summary": "Storefront browse flows are normalized here before they touch the catalog service.",
    },
    {
        "key": "commerce",
        "title": "Commerce State",
        "summary": "Mutable cart and order actions stay behind the gateway and are delegated to order_service.",
    },
    {
        "key": "ai",
        "title": "AI Assistant",
        "summary": "Customer-facing AI routes are proxied through user_service to preserve a stable website contract.",
    },
    {
        "key": "ops",
        "title": "Operations",
        "summary": "Inspection and analytics routes that help validate the gateway and downstream behavior.",
    },
)

ROUTE_DEFINITIONS = (
    {
        "id": "catalog-dashboard",
        "section": "discovery",
        "title": "Dashboard browse gateway",
        "consumer_surface": "Customer dashboard filters and search results",
        "gateway": "user_service",
        "methods": ("GET",),
        "public_paths": ("/customer/dashboard/",),
        "upstream": "product_service",
        "upstream_paths": ("/api/categories/", "/api/products/"),
        "description": "Loads category navigation and product listing data, then renders the unified storefront page.",
        "request_shape": "Query string filters: q, category, stock, price_range, sort, brand",
        "response_shape": "Rendered HTML storefront with normalized product cards and optional AI suggestions",
    },
    {
        "id": "catalog-product-detail",
        "section": "discovery",
        "title": "Product detail gateway",
        "consumer_surface": "Customer product detail page",
        "gateway": "user_service",
        "methods": ("GET",),
        "public_paths": ("/customer/products/{category_slug}/{product_id}/",),
        "upstream": "product_service",
        "upstream_paths": ("/api/products/{product_id}/",),
        "description": "Fetches one product, applies category-aware decoration, and preserves slug-based storefront URLs.",
        "request_shape": "Path params: category_slug and product_id",
        "response_shape": "Rendered HTML detail page with recommendation and chat widget context",
    },
    {
        "id": "cart-state",
        "section": "commerce",
        "title": "Cart state gateway",
        "consumer_surface": "Cart page plus add/remove cart actions",
        "gateway": "user_service",
        "methods": ("GET", "POST", "DELETE"),
        "public_paths": (
            "/customer/cart/",
            "/customer/cart/add/",
            "/customer/cart/remove/{item_id}/",
        ),
        "upstream": "order_service",
        "upstream_paths": (
            "/api/cart/",
            "/api/cart/{item_id}/",
        ),
        "description": "Keeps cart state out of user_service while preserving customer-facing cart routes.",
        "request_shape": "User-scoped cart payloads normalized in customer/services.py",
        "response_shape": "Rendered cart page plus JSON mutation responses",
    },
    {
        "id": "saved-and-compare",
        "section": "commerce",
        "title": "Saved and compare gateway",
        "consumer_surface": "Saved items and compare experiences",
        "gateway": "user_service",
        "methods": ("GET", "POST", "DELETE"),
        "public_paths": (
            "/customer/saved/",
            "/customer/saved/toggle/",
            "/customer/compare/",
            "/customer/compare/toggle/",
            "/customer/compare/remove/{item_id}/",
        ),
        "upstream": "order_service",
        "upstream_paths": (
            "/api/saved/",
            "/api/saved/toggle/",
            "/api/compare/",
            "/api/compare/toggle/",
            "/api/compare/{item_id}/",
        ),
        "description": "Delegates collection state to order_service without exposing internal endpoints to the browser.",
        "request_shape": "User id plus product payloads for toggle and removal actions",
        "response_shape": "Rendered collection pages plus JSON mutation responses",
    },
    {
        "id": "checkout-and-orders",
        "section": "commerce",
        "title": "Checkout and order gateway",
        "consumer_surface": "Checkout form, order list, and pay-order flow",
        "gateway": "user_service",
        "methods": ("GET", "POST"),
        "public_paths": (
            "/customer/checkout/",
            "/customer/orders/",
            "/customer/orders/{order_id}/pay/",
        ),
        "upstream": "order_service",
        "upstream_paths": (
            "/api/checkout/",
            "/api/orders/",
            "/api/orders/{order_id}/pay/",
        ),
        "description": "Owns browser-facing checkout and order pages while order_service remains the state authority and coordinates payment/shipping services.",
        "request_shape": "Shipping payloads and pay-order commands signed with ORDER_SERVICE_INTERNAL_KEY",
        "response_shape": "Rendered order pages plus payment and checkout result payloads",
    },
    {
        "id": "chatbot-proxy",
        "section": "ai",
        "title": "Chatbot reply proxy",
        "consumer_surface": "Floating chat widget and AI recommendation builders",
        "gateway": "user_service",
        "methods": ("POST",),
        "public_paths": ("/customer/chatbot/reply/",),
        "upstream": "chatbot_service",
        "upstream_paths": ("/api/chat/reply/",),
        "description": "Preserves the website contract while forwarding AI requests to chatbot_service.",
        "request_shape": "message, current_product, user_context, user_ref, limit",
        "response_shape": "Stable JSON contract: answer, recommendations, citations, source, fallback flags",
    },
    {
        "id": "staff-analytics-proxy",
        "section": "ops",
        "title": "Gateway analytics inspection",
        "consumer_surface": "Operational order analytics used from user_service",
        "gateway": "user_service",
        "methods": ("GET",),
        "public_paths": ("/customer/staff/analytics/",),
        "upstream": "order_service",
        "upstream_paths": ("/api/analytics/customers/",),
        "description": "Surfaces order analytics through the gateway for staff-aware operational reporting.",
        "request_shape": "customer_limit, recent_limit, range_days",
        "response_shape": "JSON analytics snapshot enriched with local user metadata",
    },
    {
        "id": "gateway-index",
        "section": "ops",
        "title": "Gateway self-inspection",
        "consumer_surface": "Operational gateway workspace and JSON registry",
        "gateway": "user_service",
        "methods": ("GET",),
        "public_paths": ("/gateway/", "/gateway/apis/"),
        "upstream": "user_service",
        "upstream_paths": (),
        "description": "Dedicated inspection surface for understanding how user_service fronts the rest of the system.",
        "request_shape": "No upstream payload; generated from local gateway metadata",
        "response_shape": "HTML workspace and JSON API index",
    },
)

CODE_LOCATIONS = (
    {
        "label": "Gateway route catalog",
        "path": "services/user_service/customer/api_gateway/definitions.py",
        "description": "Static source of truth for downstream services, route groups, and public contract metadata.",
    },
    {
        "label": "Gateway registry builder",
        "path": "services/user_service/customer/api_gateway/registry.py",
        "description": "Builds resolved URLs, sections, stats, and the JSON payload used by the dedicated gateway page.",
    },
    {
        "label": "Gateway views",
        "path": "services/user_service/customer/views.py",
        "description": "Exposes the dedicated HTML workspace at /gateway/ and the JSON index at /gateway/apis/.",
    },
)
