from decimal import Decimal


CATEGORY_FIXTURES = [
    {
        "name": "Business Laptops",
        "slug": "business-laptops",
        "description": "Reliable laptops for office, remote teams, and productivity-heavy workflows.",
        "hero_image_url": "https://images.unsplash.com/photo-1496181133206-80ce9b88a853?auto=format&fit=crop&w=1400&q=80",
        "sort_order": 10,
        "products": [
            ("Boardroom Pro 13", "Lenovo", "1299.00", 18, "Compact business laptop with quiet thermals and all-day battery."),
            ("Boardroom Pro 14", "Dell", "1399.00", 16, "Balanced office laptop with strong keyboard and stable docking."),
            ("Transit Office 14", "HP", "1199.00", 22, "Portable work laptop for spreadsheets, calls, and daily travel."),
            ("Transit Office 15", "HP", "1299.00", 20, "15-inch business model with better thermals for long sessions."),
            ("Executive Edge 14", "ASUS", "1499.00", 12, "Premium chassis with fast wake and crisp webcam output."),
            ("Executive Edge 16", "ASUS", "1699.00", 10, "Large business notebook tuned for multitasking and meetings."),
            ("ThinkDesk Carbon 14", "Lenovo", "1599.00", 14, "Lightweight premium laptop with secure sign-in and bright display."),
            ("Latitude Flow 15", "Dell", "1449.00", 13, "Dependable corporate laptop with broad accessory compatibility."),
            ("OfficeCore Flex 13", "Acer", "1049.00", 24, "Value business option with strong connectivity and clean design."),
            ("OfficeCore Flex 15", "Acer", "1149.00", 21, "Practical 15-inch laptop for finance, admin, and hybrid work."),
        ],
    },
    {
        "name": "Gaming Laptops",
        "slug": "gaming-laptops",
        "description": "High-performance gaming notebooks with dedicated graphics and cooling headroom.",
        "hero_image_url": "https://images.unsplash.com/photo-1511512578047-dfb367046420?auto=format&fit=crop&w=1400&q=80",
        "sort_order": 20,
        "products": [
            ("Vortex Arena 15", "MSI", "1899.00", 11, "Gaming laptop with fast panel and strong thermal tuning."),
            ("Vortex Arena 17", "MSI", "2199.00", 9, "Large-screen gaming machine for immersive play and streaming."),
            ("ShadowPulse 14", "ASUS", "1799.00", 12, "Portable gaming notebook with efficient graphics profile."),
            ("ShadowPulse 16", "ASUS", "2099.00", 8, "16-inch gaming platform built for sustained high frame rates."),
            ("BladeRunner 15", "Razer", "2399.00", 7, "Premium unibody gaming laptop with accurate display and power."),
            ("BladeRunner 14", "Razer", "2299.00", 6, "Travel-friendly performance system with low-latency panel."),
            ("Nebula Core 16", "Gigabyte", "1999.00", 10, "Creator-gaming crossover laptop with strong cooling."),
            ("Nebula Core 17", "Gigabyte", "2149.00", 8, "Desktop replacement for AAA games and heavy rendering."),
            ("Predator Rally 16", "Acer", "1849.00", 13, "Aggressive gaming setup with dependable frame pacing."),
            ("Predator Rally 18", "Acer", "2499.00", 5, "Oversized gaming rig for maximum thermal capacity."),
        ],
    },
    {
        "name": "Ultrabooks",
        "slug": "ultrabooks",
        "description": "Lightweight premium laptops optimized for mobility, battery life, and clean design.",
        "hero_image_url": "https://images.unsplash.com/photo-1496171367470-9ed9a91ea931?auto=format&fit=crop&w=1400&q=80",
        "sort_order": 30,
        "products": [
            ("AirLite 13", "ASUS", "999.00", 25, "Thin ultrabook for students and consultants who travel often."),
            ("AirLite 14", "ASUS", "1099.00", 23, "Portable 14-inch ultrabook with stable battery behavior."),
            ("Feather Pro 13", "Dell", "1199.00", 19, "Slim productivity laptop with premium materials and quiet fans."),
            ("Feather Pro 14", "Dell", "1299.00", 18, "Bright-display ultrabook for writing, browsing, and office work."),
            ("ZenMotion 13", "Lenovo", "1249.00", 16, "Minimal ultrabook with comfortable typing and low weight."),
            ("ZenMotion 14", "Lenovo", "1349.00", 14, "Travel-ready premium laptop with strong wireless stability."),
            ("Swift Aero 13", "Acer", "949.00", 26, "Value ultrabook with responsive everyday performance."),
            ("Swift Aero 14", "Acer", "1049.00", 24, "Lightweight daily notebook with long unplugged runtime."),
            ("Spectra Thin 13", "HP", "1399.00", 13, "Premium ultraportable for presentations and executive travel."),
            ("Spectra Thin 14", "HP", "1499.00", 12, "Elegant ultrabook with brighter panel and stronger speakers."),
        ],
    },
    {
        "name": "Smartphones",
        "slug": "smartphones",
        "description": "Modern phones for photography, communication, productivity, and social media creation.",
        "hero_image_url": "https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?auto=format&fit=crop&w=1400&q=80",
        "sort_order": 40,
        "products": [
            ("SkyPhone X", "Apple", "1099.00", 28, "Flagship phone with fast silicon and polished camera output."),
            ("SkyPhone X Max", "Apple", "1299.00", 20, "Large-display flagship with improved endurance and media comfort."),
            ("Galaxy Orbit S", "Samsung", "999.00", 30, "Balanced Android flagship with vivid display and dependable cameras."),
            ("Galaxy Orbit Ultra", "Samsung", "1299.00", 17, "High-end phone tuned for zoom photography and multitasking."),
            ("Pixel Frame 9", "Google", "899.00", 26, "Clean Android experience with smart photo processing."),
            ("Pixel Frame 9 Pro", "Google", "1099.00", 18, "Pro photography handset with brighter display and telephoto reach."),
            ("Velocity 13", "OnePlus", "799.00", 34, "Fast-charging performance phone with smooth gaming profile."),
            ("Velocity 13R", "OnePlus", "649.00", 39, "Value flagship phone with responsive software and long battery life."),
            ("Nova Lite 14", "Xiaomi", "549.00", 42, "Affordable AMOLED smartphone with practical daily speed."),
            ("Nova Lite 14 Pro", "Xiaomi", "729.00", 31, "Upgraded camera and processor for creator-friendly workflows."),
        ],
    },
    {
        "name": "Tablets",
        "slug": "tablets",
        "description": "Portable tablets for note-taking, drawing, media, and flexible productivity.",
        "hero_image_url": "https://images.unsplash.com/photo-1544244015-0df4b3ffc6b0?auto=format&fit=crop&w=1400&q=80",
        "sort_order": 50,
        "products": [
            ("Slate Pro 11", "Apple", "899.00", 19, "High-performance tablet for note-taking, drawing, and media editing."),
            ("Slate Pro 13", "Apple", "1199.00", 13, "Large premium tablet with spacious workspace and vivid panel."),
            ("Galaxy Tab Horizon 11", "Samsung", "749.00", 24, "Balanced Android tablet for work, study, and streaming."),
            ("Galaxy Tab Horizon 13", "Samsung", "999.00", 15, "Large-screen tablet with keyboard-ready multitasking mode."),
            ("Pixel Tablet Hub", "Google", "599.00", 21, "Tablet with clean software and smart home integration."),
            ("MatePad Flow 11", "Huawei", "679.00", 18, "Portable tablet with smooth pen input and office-ready layout."),
            ("MatePad Flow 13", "Huawei", "849.00", 12, "Larger creative tablet for sketching and split-screen work."),
            ("Surface Go Note", "Microsoft", "629.00", 23, "Compact Windows tablet for browsing, study, and light office work."),
            ("Surface Pro Flex", "Microsoft", "1299.00", 11, "Premium 2-in-1 tablet with productivity-class performance."),
            ("Pad Air Neo", "Xiaomi", "499.00", 28, "Value tablet for entertainment, reading, and school tasks."),
        ],
    },
    {
        "name": "Smartwatches",
        "slug": "smartwatches",
        "description": "Health, fitness, and notification-focused wearables for daily convenience.",
        "hero_image_url": "https://images.unsplash.com/photo-1523275335684-37898b6baf30?auto=format&fit=crop&w=1400&q=80",
        "sort_order": 60,
        "products": [
            ("Pulse Watch 9", "Apple", "399.00", 33, "Mainstream smartwatch with fitness tracking and polished notifications."),
            ("Pulse Watch Ultra", "Apple", "799.00", 12, "Rugged premium watch for outdoor tracking and longer battery life."),
            ("Galaxy Watch Move", "Samsung", "329.00", 29, "Balanced smartwatch for Android users focused on health metrics."),
            ("Galaxy Watch Move Pro", "Samsung", "449.00", 18, "Larger pro wearable with stronger GPS and recovery insights."),
            ("Pixel Watch Loop", "Google", "379.00", 22, "Compact smartwatch with clean software and smart assistant features."),
            ("FitSense Active", "Garmin", "499.00", 16, "Fitness-first watch with strong training metrics and stamina tracking."),
            ("FitSense Endure", "Garmin", "699.00", 9, "Adventure watch designed for endurance sports and long trips."),
            ("Amaz Track Air", "Amazfit", "219.00", 35, "Affordable smartwatch with practical battery life and wellness tools."),
            ("Amaz Track Pro", "Amazfit", "299.00", 24, "Improved GPS accuracy and display clarity for active users."),
            ("Wear Neo Lite", "Huawei", "249.00", 27, "Everyday smartwatch with clean design and broad notification support."),
        ],
    },
    {
        "name": "Audio",
        "slug": "audio",
        "description": "Headphones, earbuds, microphones, and speakers for communication and entertainment.",
        "hero_image_url": "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?auto=format&fit=crop&w=1400&q=80",
        "sort_order": 70,
        "products": [
            ("QuietBeat ANC", "Sony", "249.00", 27, "Noise-cancelling headphones for travel, focus, and meetings."),
            ("QuietBeat Studio", "Sony", "329.00", 18, "Higher-end audio tuning with broader soundstage and comfort."),
            ("AirTune Buds", "Apple", "199.00", 31, "Wireless earbuds with quick pairing and consistent daily playback."),
            ("AirTune Buds Pro", "Apple", "249.00", 22, "Improved noise cancelling and transparency for commuting."),
            ("StreamMic USB", "HyperX", "99.00", 19, "Plug-and-play condenser mic for calls, streaming, and recording."),
            ("StreamMic Plus", "HyperX", "149.00", 14, "Higher-end microphone with better gain control and clarity."),
            ("RoomPod Mini", "Google", "69.00", 42, "Compact smart speaker for bedside or desktop listening."),
            ("RoomPod Max", "Google", "149.00", 25, "Larger speaker with better low-end response for home use."),
            ("Studio Monitor One", "Audio-Technica", "179.00", 17, "Neutral over-ear headphones for editing and focused listening."),
            ("Studio Monitor Two", "Audio-Technica", "239.00", 11, "Refined monitoring headphones for creators and engineers."),
        ],
    },
    {
        "name": "Keyboards & Mice",
        "slug": "keyboards-mice",
        "description": "Input devices for productivity, ergonomic comfort, and gaming-adjacent responsiveness.",
        "hero_image_url": "https://images.unsplash.com/photo-1511467687858-23d96c32e4ae?auto=format&fit=crop&w=1400&q=80",
        "sort_order": 80,
        "products": [
            ("TypeFlow TKL", "Keychron", "119.00", 29, "Compact mechanical keyboard with wireless flexibility."),
            ("TypeFlow Full", "Keychron", "129.00", 24, "Full-size productivity keyboard with comfortable switches."),
            ("DeskMouse Ergo", "Logitech", "79.00", 37, "Ergonomic mouse tuned for long office sessions."),
            ("DeskMouse Master", "Logitech", "109.00", 28, "Precision productivity mouse with multi-device switching."),
            ("Arena Mouse Lite", "Razer", "69.00", 31, "Responsive gaming-style mouse for fast pointer control."),
            ("Arena Mouse Pro", "Razer", "99.00", 21, "Higher-end sensor and lighter shell for advanced users."),
            ("QuietKeys Slim", "Microsoft", "59.00", 33, "Silent keyboard for offices, libraries, and shared spaces."),
            ("QuietKeys Combo", "Microsoft", "89.00", 26, "Wireless keyboard and mouse combo for home office setups."),
            ("Creator Pad Mini", "Logitech", "129.00", 15, "Compact keypad and dial control for editors and designers."),
            ("Creator Pad Pro", "Logitech", "179.00", 10, "Expanded creator control pad with deeper shortcut support."),
        ],
    },
    {
        "name": "Chargers & Cables",
        "slug": "chargers-cables",
        "description": "Charging accessories, travel power gear, and essential connectivity tools.",
        "hero_image_url": "https://images.unsplash.com/photo-1583394838336-acd977736f90?auto=format&fit=crop&w=1400&q=80",
        "sort_order": 90,
        "products": [
            ("PowerBrick 65W", "Anker", "49.00", 63, "Compact charger for phones, tablets, and light laptops."),
            ("PowerBrick 100W", "Anker", "69.00", 47, "GaN charger with enough power for creator notebooks."),
            ("MagPad Duo", "Belkin", "79.00", 35, "Wireless charging pad for phone and smartwatch combos."),
            ("MagPad Travel", "Belkin", "59.00", 41, "Foldable wireless charger designed for travel bags."),
            ("CableFlex USB-C 1m", "UGREEN", "15.00", 110, "Braided everyday USB-C cable for fast charging."),
            ("CableFlex USB-C 2m", "UGREEN", "19.00", 98, "Longer USB-C cable for desks and bedside charging."),
            ("DisplayLink USB-C HDMI", "UGREEN", "29.00", 56, "Video cable for monitors, TVs, and conference rooms."),
            ("DockCharge 7-in-1", "Anker", "99.00", 24, "Travel dock with HDMI, USB-A, card slots, and passthrough power."),
            ("TravelPlug Global", "Mophie", "39.00", 52, "Universal travel adapter with USB charging support."),
            ("CableKit Organizer", "Native Union", "25.00", 67, "Cable management pack for backpacks and desk setups."),
        ],
    },
    {
        "name": "Bags & Stands",
        "slug": "bags-stands",
        "description": "Carry gear, protective bags, and stands that improve comfort and mobility.",
        "hero_image_url": "https://images.unsplash.com/photo-1553062407-98eeb64c6a62?auto=format&fit=crop&w=1400&q=80",
        "sort_order": 100,
        "products": [
            ("Commute Pack 16", "Peak Design", "189.00", 17, "Tech backpack with modular compartments for daily carry."),
            ("Commute Pack 20", "Peak Design", "219.00", 11, "Larger carry bag for creators with extra camera space."),
            ("Shield Sleeve 13", "Tomtoc", "35.00", 54, "Protective laptop sleeve for smaller ultraportables."),
            ("Shield Sleeve 16", "Tomtoc", "39.00", 46, "Larger padded sleeve for business and gaming notebooks."),
            ("LiftStand Fold", "Twelve South", "59.00", 31, "Portable laptop stand for better posture and airflow."),
            ("LiftStand Pro", "Twelve South", "89.00", 20, "More stable stand for fixed desks and multi-hour sessions."),
            ("Tablet Rest Mini", "MOFT", "39.00", 43, "Compact folding stand for tablets, e-readers, and phones."),
            ("Tablet Rest Pro", "MOFT", "59.00", 28, "Adjustable stand for desk calls and content viewing."),
            ("Desk Arm Vision", "BenQ", "129.00", 14, "Monitor and laptop support arm for cleaner ergonomic setups."),
            ("Travel Pouch Kit", "Native Union", "49.00", 33, "Organized pouch for chargers, dongles, and small accessories."),
        ],
    },
]


def iter_seed_rows():
    for category in CATEGORY_FIXTURES:
        for index, product in enumerate(category["products"], start=1):
            name, brand, price, stock, description = product
            yield {
                "category": {
                    "name": category["name"],
                    "slug": category["slug"],
                    "description": category["description"],
                    "hero_image_url": category["hero_image_url"],
                    "sort_order": category["sort_order"],
                    "is_active": True,
                },
                "product": {
                    "name": name,
                    "brand": brand,
                    "description": description,
                    "image_url": f"{category['hero_image_url']}&product={index}",
                    "price": Decimal(price),
                    "stock": stock,
                },
            }
